services:
  evolution_db:
    image: postgres:15-alpine
    restart: always
    container_name: evolution_db
    environment:
      POSTGRES_USER: guilherme_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: evolution_automation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  evolution_client:
    image: postgres:15-alpine
    restart: always
    container_name: evolution_client
    environment:
      POSTGRES_USER: guilherme_client
      POSTGRES_PASSWORD: root
      POSTGRES_DB: evolution_client
    volumes:
      - postgres_data_client:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  evolution:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_URL: http://localhost:8080
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://guilherme_admin:root@evolution_db:5432/evolution_automation

      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_HOST: redis
      CACHE_REDIS_PORT: "6379"
      CACHE_REDIS_DB: "0"
      CACHE_REDIS_URI: redis://redis:6379/0

      AUTHENTICATION_API_KEY: 7996256f-dfb9-4028-9fa3-1ed9a2f8b640
    depends_on:
      - evolution_db
      - redis

  nextjs:
    build:
      context: ./client2
    container_name: atendimento_next
    ports:
      - "3000:3000"
    volumes:
      - ./client2:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://guilherme_client:root@evolution_client:5432/evolution_client
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - evolution_client

volumes:
  postgres_data:
  postgres_data_client:
  redis_data: